/*
 * srm32f446xx_i2c_driver.c
 *
 *  Created on: Mar 6, 2026
 *      Author: Abhishek Patil
 */

#include "stm32f446xx_i2c_driver.h"


 void I2C_GenerateStartCondition(I2C_RegDef_t *pI2Cx);
static void I2C_ExecuteAddressPhaseWrite(I2C_RegDef_t *pI2Cx, uint8_t SlaveAddr);
static void I2C_ExecuteAddressPhaseRead(I2C_RegDef_t *pI2Cx, uint8_t SlaveAddr);
static void I2C_ClearADDRFlag(I2C_Handle_t *pI2CHandle);




 void I2C_GenerateStartCondition(I2C_RegDef_t *pI2Cx) {
	pI2Cx->I2C_CR1 |= (1 << I2C_CR1_START);
}


/*********************************************************************
 * @fn      		  - I2C_ExecuteAddressPhaseWrite
 *
 * @brief             - Executes the address phase for I2C master write operation.
 *                      Sends the slave address along with write bit (0)
 *                      on the I2C bus.
 *
 * @param[in]         - pI2Cx     : Pointer to I2C peripheral registers
 * @param[in]         - SlaveAddr : 7-bit address of the slave device
 *
 * @return            - None
 *
 * @Note              - This function is called after generating START condition.
 *
 *                      It performs the following:
 *                      - Shifts slave address to align with address field
 *                      - Clears LSB (write operation → 0)
 *                      - Writes address into DR register
 *
 *********************************************************************/

static void I2C_ExecuteAddressPhaseWrite(I2C_RegDef_t *pI2Cx, uint8_t SlaveAddr) {
	SlaveAddr = SlaveAddr << 1;  //this make a space for the read write bit
	SlaveAddr &= ~(1); //slave addr is slave addr + r/w bit  //setting the 0th bit for means for the write
	pI2Cx->I2C_DR = SlaveAddr;
}


/**
 * @brief  Executes the address phase for I2C READ operation.
 *
 * @param  pI2Cx      Pointer to I2C peripheral registers
 * @param  SlaveAddr  7-bit slave address
 *
 * @details
 * The I2C protocol uses a 7-bit slave address followed by a 1-bit
 * Read/Write (R/W) control bit.
 *
 * This function:
 * 1. Left shifts the 7-bit slave address by 1 to make space for R/W bit.
 * 2. Sets the least significant bit (LSB) to 1 to indicate READ operation.
 * 3. Writes the final 8-bit value into the data register (DR),
 *    which initiates address transmission on the I2C bus.
 *
 * Example:
 *   SlaveAddr = 0x50 (0101 0000)
 *   After shift  -> 1010 0000
 *   After OR 1   -> 1010 0001 (0xA1)
 *
 * Final transmitted value = (SlaveAddr << 1) | 1
 *
 * Note:
 *   LSB = 0 → Write operation
 *   LSB = 1 → Read operation
 */

static void I2C_ExecuteAddressPhaseRead(I2C_RegDef_t *pI2Cx, uint8_t SlaveAddr) {
	SlaveAddr = SlaveAddr << 1;  //this make a space for the read write bit
	SlaveAddr |= 1; //slave addr is slave addr + r/w bit  //setting the 0th bit for means for the read
	pI2Cx->I2C_DR = SlaveAddr;
}

/*********************************************************************
 * @fn      		  - I2C_ClearADDRFlag
 *
 * @brief             - Clears the ADDR (Address Matched) flag in I2C.
 *                      This flag is set when address phase is completed.
 *
 * @param[in]         - pI2CHandle : Pointer to I2C handle structure
 *
 * @return            - None
 *
 * @Note              - ADDR flag must be cleared by reading SR1 followed
 *                      by reading SR2 register.
 *
 *                      This function handles both master and slave modes
 *                      and ensures proper clearing to continue communication.
 *
 *********************************************************************/

static void I2C_ClearADDRFlag(I2C_Handle_t *pI2CHandle) {
	uint32_t dummy_read;
	//cheal the device mode
	if (pI2CHandle->pI2Cx->I2C_SR2 & (1 << I2C_SR2_MSL)) {
		//device in master mode
		if (pI2CHandle->TxRRxState == I2C_BUSY_IN_RX) {
			if (pI2CHandle->RxSize == 1) {
				//1.first disable the ack
				I2C_ManageAcking(pI2CHandle->pI2Cx, DISABLE);

				//clear the addr flag(read sr1,read sr2)
				dummy_read = pI2CHandle->pI2Cx->I2C_SR1;
				dummy_read = pI2CHandle->pI2Cx->I2C_SR2;
				(void) dummy_read; //it means that the variable is unused so compiler not genrate an error

			}
		} else {
			//for master sending the data
			dummy_read = pI2CHandle->pI2Cx->I2C_SR1;
			dummy_read = pI2CHandle->pI2Cx->I2C_SR2;
			(void) dummy_read;
		}

	} else {
		//device is in slave mode
		dummy_read = pI2CHandle->pI2Cx->I2C_SR1;
		dummy_read = pI2CHandle->pI2Cx->I2C_SR2;
		(void) dummy_read;

	}

}




 void I2C_GenerateStopCondition(I2C_RegDef_t *pI2Cx) {
	pI2Cx->I2C_CR1 |= (1 << I2C_CR1_STOP);

}

/************************************************************
 * @fn         RCC_GetPLLOutputClock
 *
 * @brief      Calculates and returns the clock frequency
 *             generated by the PLL (Phase Locked Loop).
 *
 * @param[in]  None
 *
 * @return     PLL output clock frequency in Hz
 *
 * @details    The PLL is used to generate higher system clock
 *             frequencies by multiplying the input clock source
 *             (HSI or HSE). This function reads the PLL
 *             configuration registers and calculates the final
 *             PLL output frequency.
 *
 * @use_case
 *             - Used when the system clock source is PLL.
 *             - Required for calculating derived clocks such as
 *               AHB, APB1, and APB2 peripheral clocks.
 *             - Needed when configuring peripherals that depend
 *               on accurate clock values such as:
 *                 • I2C
 *                 • I2C
 *                 • USART
 *                 • Timers
 *
 * @note       This function must read PLL configuration fields
 *             such as PLLM, PLLN, PLLP from RCC registers to
 *             compute the final clock frequency.
 *
 ************************************************************/





//PERIPHERAL CLOCK SETUP

/************************************************************
 * @fn         I2C_PeriClockControl
 *
 * @brief      Enables or disables the peripheral clock for
 *             the specified I2C peripheral.
 *
 * @param[in]  pI2Cx  : Base address of the I2C peripheral
 *                      (e.g., I2C1, I2C2, I2C3)
 *
 * @param[in]  EnorDi : Enable or Disable macro
 *                      ENABLE  - Enables I2C peripheral clock
 *                      DISABLE - Disables I2C peripheral clock
 *
 * @return     None
 *
 * @note       This function configures the corresponding
 *             I2C clock in the RCC (Reset and Clock Control)
 *             register. The peripheral clock must be enabled
 *             before configuring the I2C registers.
 *
 ************************************************************/

void I2C_PeriClockControl(I2C_RegDef_t *pI2Cx, uint8_t EnorDi) {
	if (EnorDi == ENABLE) {
		if (pI2Cx == I2C1) {
			I2C1_PCLK_EN();
		} else if (pI2Cx == I2C2) {
			I2C2_PCLK_EN();
		} else if (pI2Cx == I2C3) {
			I2C3_PCLK_EN();
		}

	} else {
		if (pI2Cx == I2C1) {
			I2C1_PCLK_DI();
		} else if (pI2Cx == I2C2) {
			I2C2_PCLK_DI();
		} else if (pI2Cx == I2C3) {
			I2C3_PCLK_DI();
		}
	}

}

/************************************************************
 * @fn         I2C_Init
 *
 * @brief      Initializes the I2C peripheral with the
 *             specified configuration settings.
 *
 * @param[in]  pI2CHandle : Pointer to the I2C handle structure
 *                          which contains the base address of
 *                          the I2C peripheral and configuration
 *                          parameters.
 *
 * @return     None
 *
 * @note       This function configures various I2C registers
 *             such as CR1, CR2, OAR1, and CCR based on the
 *             configuration provided in the handle structure.
 *
 ************************************************************/

void I2C_Init(I2C_Handle_t *pI2CHandle) {

	I2C_PeriClockControl(pI2CHandle->pI2Cx, ENABLE);
	uint32_t tempreg = 0;
	tempreg |= (pI2CHandle->I2C_Config.I2C_AckControl << 10);
	pI2CHandle->pI2Cx->I2C_CR1 = tempreg;

	//configure the FREQ field of CR2
	tempreg = 0;
	tempreg |= RCC_GetPCLK1Value() / 1000000U; //converting from hz to mhz by dividing
	pI2CHandle->pI2Cx->I2C_CR2 = (tempreg & 0x3F);//“We mask with 0x3F to ensure only the valid 6-bit FREQ value is written into the CR2 register.

	//program the device own address  when stm32 act as slave
	tempreg = 0;
	tempreg |= pI2CHandle->I2C_Config.I2C_DeviceAddress << 1;
	tempreg |= (1 << 14);   //must be kept one if not divice dont work properly
	pI2CHandle->pI2Cx->I2C_OAR1 = tempreg;

	//CCR calculation   clock control register (how fast scl will run) high ccr -> slow clock low ccr->faster clock
	uint16_t ccr_value = 0;
	tempreg = 0;
	if (pI2CHandle->I2C_Config.I2C_SCL_Speed <= I2C_SCL_SPEED_SM) {
		//Mode Is Standard Mode
		ccr_value = (RCC_GetPCLK1Value()
				/ (2 * pI2CHandle->I2C_Config.I2C_SCL_Speed));
		tempreg |= (ccr_value & 0xFFF);
	} else {
		//Mode is fast mode
		tempreg |= (1 << 15);
		tempreg |= (pI2CHandle->I2C_Config.I2C_FMDutyCycle << 14);
		if (pI2CHandle->I2C_Config.I2C_FMDutyCycle == I2C_FM_DUTY_2) {
			ccr_value = (RCC_GetPCLK1Value()
					/ (3 * pI2CHandle->I2C_Config.I2C_SCL_Speed));
		} else {
			ccr_value = (RCC_GetPCLK1Value()
					/ (25 * pI2CHandle->I2C_Config.I2C_SCL_Speed));

		}

		tempreg |= (ccr_value & 0xFFF);
	}

	pI2CHandle->pI2Cx->I2C_CCR = tempreg;

	//TRISE configuration maximum rise time setting

	if (pI2CHandle->I2C_Config.I2C_SCL_Speed <= I2C_SCL_SPEED_SM) {
		//Mode Is Standard Mode
		tempreg = (RCC_GetPCLK1Value() / 1000000U) + 1;//Max rise time = 1000 ns (1 µs) 100000U=Tpclk=Tpclk1 = 1 / PCLK1
	} else {
		//mode is fast mode  TRISE = (300 ns / Tpclk1) + 1
		tempreg = (RCC_GetPCLK1Value() * 300 / 1000000000U) + 1;//Max rise time = 300 ns (fast mode)
	}

	// Write the rise time value to the I2C TRISE register.
	// Mask with 0x3F to keep only the lower 6 bits because TRISE register uses only 6 bits.
	pI2CHandle->pI2Cx->I2C_TRISE = (tempreg & 0x3F);
}

/************************************************************
 * @fn         I2C_DeInit
 *
 * @brief      Resets the selected I2C peripheral registers
 *             to their default reset values.
 *
 * @param[in]  pI2Cx : Base address of the I2C peripheral
 *
 * @return     None
 *
 * @note       This function performs a peripheral reset using
 *             the RCC reset register.
 *
 ************************************************************/

void I2C_DeInit(I2C_RegDef_t *pI2Cx) {
	if (pI2Cx == I2C1) {
		I2C1_REG_RESET();
	} else if (pI2Cx == I2C2) {
		I2C2_REG_RESET();
	} else if (pI2Cx == I2C3) {
		I2C3_REG_RESET();
	}

}

/************************************************************
 * @fn         I2C_GetFlagStatus
 *
 * @brief      Checks whether a specified I2C status flag is set or not.
 *
 * @param[in]  pI2Cx    : Pointer to the base address of the
 *                        I2C peripheral (I2C1, I2C2, I2C3)
 *
 * @param[in]  FlagName : Specifies the flag to check.
 *                        This parameter can be one of the
 *                        I2C status flags (e.g., I2C_FLAG_TXE,
 *                        I2C_FLAG_RXNE, I2C_FLAG_SB, etc.)
 *
 * @return     FLAG_SET   : If the specified flag is set
 *             FLAG_RESET : If the specified flag is cleared
 *
 * @note       This function reads the I2C status register (SR1)
 *             and performs a bitwise AND operation with the
 *             given flag to determine its status.
 *
 *             The status flags are set and cleared by hardware
 *             events; this function only reads the flag status.
 *
 ************************************************************/

uint8_t I2C_GetFlagStatus(I2C_RegDef_t *pI2Cx, uint32_t FlagName) {
	if (pI2Cx->I2C_SR1 & FlagName) {
		return FLAG_SET;
	}

	return FLAG_RESET;
}

/************************************************************
 * @fn         I2C_MasterSendData
 *
 * @brief      Sends data from master to a slave device over I2C.
 *
 * @param[in]  pI2CHandle : Pointer to the I2C handle structure
 *                          containing configuration and base
 *                          address of the I2C peripheral
 *
 * @param[in]  pTxBuffer  : Pointer to the transmit buffer
 *                          containing data to be sent
 *
 * @param[in]  Len        : Length of data to be transmitted
 *
 * @param[in]  SlaveAddr  : 7-bit address of the slave device
 *
 * @return     None
 *
 * @note       This is a blocking (polling-based) API.
 *             The function performs the following steps:
 *
 *             1. Generates the START condition
 *             2. Sends the slave address with write request
 *             3. Waits for address phase completion (ADDR flag)
 *             4. Clears ADDR flag by reading SR1 and SR2
 *             5. Sends data byte-by-byte
 *             6. Waits for TXE (data register empty)
 *             7. Waits for BTF (byte transfer finished)
 *             8. Generates STOP condition
 *
 *             All status flags (SB, ADDR, TXE, BTF) are
 *             handled using polling.
 *
 ************************************************************/

void I2C_MasterSendData(I2C_Handle_t *pI2CHandle, uint8_t *pTxBuffer,
		uint8_t Len, uint8_t SlaveAddr, uint8_t sr) {
	//1 Genrate a start condition
	I2C_GenerateStartCondition(pI2CHandle->pI2Cx);

	//2.confirm that start genration is completed by cheaking the SB flag in the SR1
	// Note: untill SB is cleared SCL will be streched (pulled to low)

	while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_SB))
		;

	//3 send the address of the slave with r/w bit set to w(0) (total 8 bits)
	I2C_ExecuteAddressPhaseWrite(pI2CHandle->pI2Cx, SlaveAddr);

	//4.confirm that address phase is completed by cheaking the addr flag in the SR1
	while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_ADDR))
		;

	//5.clear the ADDR flag accorrding to its softwere sequence
	//Note: untill ADDR is cleared SCL will be stretched(pulled to low)
	I2C_ClearADDRFlag(pI2CHandle);

	//6. send the data untill len becomes 0

	while (Len > 0) {
		while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_TXE))
			;	 // wait until TXE is set means data register is empty
		pI2CHandle->pI2Cx->I2C_DR = *pTxBuffer;
		pTxBuffer++;
		Len--;
	}

	//7.when len becomes zero wait for txe=1 and btf=1 before gernarating the stop condition
	//Note. TXE =1,BTF=1,means that both SR and DR are empty and next transmission should begin
	//when BTF=1 SCL will be streched (pulled to low)

	while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_TXE))
		;

	while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_BTF))
		;

	//8. Genrate stop condition and master need to wait for the completion of stop condition
	// Note.genrating stop,automatically clears the btf

	if (sr == I2C_DISABLE_SR)
		I2C_GenerateStopCondition(pI2CHandle->pI2Cx);

}

/************************************************************
 * @fn         I2C_MasterReceiveData
 *
 * @brief      Receives data from a slave device over I2C
 *             in master mode.
 *
 * @param[in]  pI2CHandle : Pointer to the I2C handle structure
 *                          containing configuration and base
 *                          address of the I2C peripheral
 *
 * @param[out] pRxBuffer  : Pointer to the buffer where received
 *                          data will be stored
 *
 * @param[in]  Len        : Number of bytes to be received
 *
 * @param[in]  SlaveAddr  : 7-bit address of the slave device
 *
 * @return     None
 *
 * @note       This is a blocking (polling-based) API.
 *             The function performs the following steps:
 *
 *             1. Generates the START condition
 *             2. Sends the slave address with read request
 *             3. Waits for ADDR flag (address phase complete)
 *             4. Clears ADDR flag by reading SR1 and SR2
 *
 *             If Len == 1:
 *                - Disable ACK
 *                - Clear ADDR
 *                - Generate STOP
 *                - Wait for RXNE
 *                - Read data
 *
 *             If Len > 1:
 *                - Enable ACK
 *                - For each byte:
 *                    • Wait for RXNE
 *                    • Read data
 *                - Before last byte:
 *                    • Disable ACK
 *                    • Generate STOP
 *
 *             RXNE flag indicates data available in DR.
 *
 *             ACK control is critical to properly terminate
 *             reception and avoid extra bytes from slave.
 *
 ************************************************************/

void I2C_MasterReceiveData(I2C_Handle_t *pI2CHandle, uint8_t *pRxBuffer,
		uint8_t Len, uint8_t SlaveAddr, uint8_t sr) {
	//1.Genrate the START condition
	I2C_GenerateStartCondition(pI2CHandle->pI2Cx);

	//2.confirm that start genration is completed by cheaking the SB flag in the SR1
	// Note: untill SB is cleared SCL will be streched (pulled to low)

	while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_SB))
		;

	//3 send the address of the slave with r/w bit set to r(1) (total 8 bits)
	I2C_ExecuteAddressPhaseRead(pI2CHandle->pI2Cx, SlaveAddr);

	//4.confirm that address phase is completed by cheaking the addr flag in the SR1
	while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_ADDR))
		;

	//procedure to read only 1 byte from slave
	if (Len == 1) {
		//disable the acking
		I2C_ManageAcking(pI2CHandle->pI2Cx, I2C_ACK_DISABLE);

		//clear the ADDR flag
		I2C_ClearADDRFlag(pI2CHandle);

		//wait until RXNE becomes 1
		while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_RXNE))
			;	// wait until RXNE is set means data register is empty

		//genrate STOP condition
		if (sr == I2C_DISABLE_SR)
			I2C_GenerateStopCondition(pI2CHandle->pI2Cx);

		//read data in to buffer

		*pRxBuffer = pI2CHandle->pI2Cx->I2C_DR;

	}

	//procedure to read data from slave when  (Len > 1)

	if (Len > 1) {
		//clear the ADDR flag
		I2C_ClearADDRFlag(pI2CHandle);

		//read the data untill Len becomes zero
		for (uint32_t i = Len; i > 0; i--) {
			//wait untill Rxne becomes 1
			while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_RXNE))
				;	// wait until RXNE is set means data register is empty

			if (i == 2) //if last 2 bytes are remaining
					{
				//clear the ack bit
				I2C_ManageAcking(pI2CHandle->pI2Cx, I2C_ACK_DISABLE);

				//genrate the STOP condition
				if (sr == I2C_DISABLE_SR)
					I2C_GenerateStopCondition(pI2CHandle->pI2Cx);

			}

			//read the data from the data register in to buffer
			*pRxBuffer = pI2CHandle->pI2Cx->I2C_DR;

			//increment the buffer
			pRxBuffer++;

		}

	}

//re-enable the acking
	if (pI2CHandle->I2C_Config.I2C_AckControl == I2C_ACK_ENABLE) {
		I2C_ManageAcking(pI2CHandle->pI2Cx, I2C_ACK_ENABLE);

	}

}

/************************************************************
 * @fn         I2C_IRQInterruptConfig
 *
 * @brief      Enables or disables the interrupt for the
 *             specified IRQ number.
 *
 * @param[in]  IRQNumber : IRQ number of the interrupt
 *
 * @param[in]  EnorDi    : Enable or Disable macro
 *                         ENABLE  - Enables interrupt
 *                         DISABLE - Disables interrupt
 *
 * @return     None
 *
 * @note       This function configures the interrupt enable
 *             registers of the NVIC controller.
 *
 ************************************************************/

void I2C_IRQInterruptConfig(uint8_t IRQNumber, uint8_t EnorDi) {

	if (EnorDi == ENABLE) {
		if (IRQNumber <= 31) {
			//Program For ISRE0 Register
			*NVIC_ISER0 |= (1 << IRQNumber);

		} else if (IRQNumber > 31 && IRQNumber < 64) {

			//Program For ISER1 Register (32 to 63 )
			*NVIC_ISER1 |= (1 << (IRQNumber % 32));

		} else if (IRQNumber >= 64 && IRQNumber < 96) {
			//Program For ISRE2 Register  (64 to 95 )
			*NVIC_ISER2 |= (1 << (IRQNumber % 64));

		}
	} else {

		if (IRQNumber <= 31) {
			//Program For ICER0) Register
			*NVIC_ICER0 |= (1 << IRQNumber);

		} else if (IRQNumber > 31 && IRQNumber < 64) {

			//Program For ICER1 Register (32 to 63 )
			*NVIC_ICER1 |= (1 << (IRQNumber % 32));

		} else if (IRQNumber >= 64 && IRQNumber < 96) {
			//Program For ICER2 Register  (64 to 95 )
			*NVIC_ICER2 |= (1 << (IRQNumber % 64));

		}
	}

}

/************************************************************
 * @fn         I2C_IRQPriorityConfig
 *
 * @brief      Configures the priority level of a given
 *             interrupt.
 *
 * @param[in]  IRQNumber   : IRQ number of the interrupt
 *
 * @param[in]  IRQPriority : Priority level to be assigned
 *
 * @return     None
 *
 * @note       Lower priority number indicates higher
 *             interrupt priority.
 *
 ************************************************************/

void I2C_IRQPriorityConfig(uint8_t IRQNumber, uint32_t IRQPriority) {
	uint8_t iprx = IRQNumber / 4;
	uint8_t iprx_section = IRQNumber % 4;
	uint8_t shift_amount = (8 * iprx_section) + (8 - NO_PR_BITS_IMPLEMENTED);
	// it jump to that ipr register address  :here 1st we are finding which ipr address is this and  then we are jumping to that register address by adding the (ipsr *4 ) (4 beacuse reg is of 32 bit) value to the base  address
	*(NVIC_PR_BASE_ADDR + iprx) |= (IRQPriority << shift_amount);

}

/************************************************************
 * @fn         I2C_PeripheralControl
 *
 * @brief      Enables or disables the I2C peripheral.
 *
 * @param[in]  pI2Cx  : Base address of the I2C peripheral
 *
 * @param[in]  EnorDi : Enable or Disable macro
 *                      ENABLE  - Enables I2C peripheral
 *                      DISABLE - Disables I2C peripheral
 *
 * @return     None
 *
 * @note       This function controls the PE (Peripheral Enable)
 *             bit in the I2C CR1 register.
 *
 ************************************************************/

void I2C_PeripheralControl(I2C_RegDef_t *pI2Cx, uint8_t EnorDi) {
	if (EnorDi == ENABLE) {
		pI2Cx->I2C_CR1 |= (1 << I2C_CR1_PE);
	} else {
		pI2Cx->I2C_CR1 &= ~(1 << I2C_CR1_PE);

	}
}

/************************************************************
 * @fn         I2C_ManageAcking
 *
 * @brief      Enables or disables ACK (acknowledge) control
 *             for the I2C peripheral.
 *
 * @param[in]  pI2Cx  : Pointer to the base address of the
 *                      I2C peripheral (I2C1, I2C2, I2C3)
 *
 * @param[in]  EnorDi : ENABLE  -> Enable ACK
 *                      DISABLE -> Disable ACK
 *
 * @return     None
 *
 * @note       ACK is used during I2C data reception to inform
 *             the transmitter (slave) whether more data is
 *             expected.
 *
 *             When ACK is enabled:
 *                - Master sends ACK after receiving each byte
 *                - Used when receiving multiple bytes
 *
 *             When ACK is disabled:
 *                - Master sends NACK after receiving a byte
 *                - Typically used before receiving the last byte
 *                  to indicate end of reception
 *
 *             This function configures the ACK bit in the CR1
 *             register of the I2C peripheral.
 *
 ************************************************************/

void I2C_ManageAcking(I2C_RegDef_t *pI2Cx, uint8_t EnorDi) {
	if (EnorDi == I2C_ACK_ENABLE) {
		// enable the ACK
		pI2Cx->I2C_CR1 |= (1 << I2C_CR1_ACK);

	} else {
		//disable the ACK
		pI2Cx->I2C_CR1 &= ~(1 << I2C_CR1_ACK);

	}
}

/*********************************************************************
 * @fn      		  - I2C_MasterSendDataIT
 *
 * @brief             - Initiates I2C master transmission in interrupt mode.
 *                      This function configures the I2C peripheral to send
 *                      data to a slave device without blocking the CPU.
 *                      The transmission is handled using I2C interrupts.
 *
 * @param[in]         - pI2CHandle : Pointer to I2C handle structure which
 *                                  contains configuration, buffer pointers,
 *                                  state information, and I2C peripheral base address
 *
 * @param[in]         - pTxBuffer  : Pointer to the transmit buffer which holds
 *                                  the data to be sent to the slave device
 *
 * @param[in]         - Len        : Total number of bytes to be transmitted
 *
 * @param[in]         - SlaveAddr  : 7-bit address of the slave device
 *                                  to which data will be transmitted
 *
 * @param[in]         - Sr         : Repeated start condition control
 *                                  I2C_ENABLE_SR  -> Repeated start will be generated
 *                                  I2C_DISABLE_SR -> Stop condition will be generated
 *                                                    after transmission completes
 *
 * @return            - Returns the previous state of the I2C peripheral:
 *                      I2C_READY       -> Peripheral is ready for communication
 *                      I2C_BUSY_IN_TX  -> Transmission is already in progress
 *
 * @Note              - This is a non-blocking (interrupt-based) API.
 *                      The function only initializes the transmission.
 *                      Actual data transfer is handled inside ISR.
 *
 *                      The following interrupts are used:
 *                      - TXE (Transmit buffer empty)
 *                      - BTF (Byte transfer finished)
 *                      - STOPF (Stop detection, if applicable)
 *                      - Error interrupts (Bus error, arbitration lost, etc.)
 *
 *                      Internal members updated:
 *                      - pTxBuffer  -> Stores transmit buffer address
 *                      - TxLen      -> Stores remaining data length
 *                      - TxRxState  -> Set to I2C_BUSY_IN_TX
 *                      - DevAddr    -> Stores slave address
 *
 *                      User must implement:
 *                      I2C_ApplicationEventCallback()
 *                      to handle transmission complete and error events.
 *
 *********************************************************************/
uint8_t I2C_MasterSendDataIT(I2C_Handle_t *pI2CHandle, uint8_t *pTxBuffer,
		uint8_t Len, uint8_t SlaveAddr, uint8_t Sr) {

	uint8_t busystate = pI2CHandle->TxRRxState;

	if ((busystate != I2C_BUSY_IN_TX) && (busystate != I2C_BUSY_IN_RX)) {
		pI2CHandle->pTxBuffer = pTxBuffer;
		pI2CHandle->TxLen = Len;
		pI2CHandle->TxRRxState = I2C_BUSY_IN_TX;
		pI2CHandle->DevAddr = SlaveAddr;
		pI2CHandle->sr = Sr;

		//Implement code to Generate START Condition
		I2C_GenerateStartCondition(pI2CHandle->pI2Cx);

		//Implement the code to enable ITBUFEN Control Bit
		pI2CHandle->pI2Cx->I2C_CR2 |= (1 << I2C_CR2_ITBUFEN);

		//Implement the code to enable ITEVFEN Control Bit
		pI2CHandle->pI2Cx->I2C_CR2 |= (1 << I2C_CR2_ITEVTEN);

		//Implement the code to enable ITERREN Control Bit
		pI2CHandle->pI2Cx->I2C_CR2 |= (1 << I2C_CR2_ITERREN);

	}

	return busystate;

}

/*********************************************************************
 * @fn      		  - I2C_MasterReceiveDataIT
 *
 * @brief             - Initiates I2C master reception in interrupt mode.
 *                      This function configures the I2C peripheral and
 *                      enables required interrupts to receive data
 *                      asynchronously from a slave device.
 *
 * @param[in]         - pI2CHandle : Pointer to I2C handle structure
 *                                  containing configuration and state info
 *
 * @param[in]         - pRxBuffer  : Pointer to receive buffer where
 *                                  incoming data will be stored
 *
 * @param[in]         - Len        : Length of data to be received (in bytes)
 *
 * @param[in]         - SlaveAddr  : 7-bit address of the slave device
 *
 * @param[in]         - Sr         : Repeated start control
 *                                  I2C_ENABLE_SR  -> Generate repeated start
 *                                  I2C_DISABLE_SR -> Generate stop condition
 *
 * @return            - uint8_t
 *                      Returns current state of I2C before starting transfer:
 *                      I2C_BUSY_IN_RX  -> Reception ongoing
 *                      I2C_READY       -> Peripheral ready
 *
 * @Note              - This is a non-blocking API. Data reception is handled
 *                      through interrupts (RXNE, STOPF, etc.).
 *
 *                      Application must implement the callback:
 *                      I2C_ApplicationEventCallback()
 *                      to handle completion or error events.
 *
 *                      Interrupts used:
 *                      - I2C_EV interrupt (Event)
 *                      - I2C_ER interrupt (Error)
 *
 *                      Internally updates:
 *                      - pRxBuffer
 *                      - RxLen
 *                      - RxSize
 *                      - TxRxState
 *
 *********************************************************************/
uint8_t I2C_MasterReceiveDataIT(I2C_Handle_t *pI2CHandle, uint8_t *pRxBuffer,
		uint8_t Len, uint8_t SlaveAddr, uint8_t Sr) {

	uint8_t busystate = pI2CHandle->TxRRxState;

	if ((busystate != I2C_BUSY_IN_TX) && (busystate != I2C_BUSY_IN_RX)) {
		pI2CHandle->pRxBuffer = pRxBuffer;
		pI2CHandle->RxLen = Len;
		pI2CHandle->TxRRxState = I2C_BUSY_IN_RX;
		pI2CHandle->RxSize = Len; //Rxsize is used in the ISR code to manage the data reception
		pI2CHandle->DevAddr = SlaveAddr;
		pI2CHandle->sr = Sr;

		//Implement code to Generate START Condition
		I2C_GenerateStartCondition(pI2CHandle->pI2Cx);

		//Implement the code to enable ITBUFEN Control Bit
		pI2CHandle->pI2Cx->I2C_CR2 |= (1 << I2C_CR2_ITBUFEN);

		//Implement the code to enable ITEVFEN Control Bit
		pI2CHandle->pI2Cx->I2C_CR2 |= (1 << I2C_CR2_ITEVTEN);

		//Implement the code to enable ITERREN Control Bit
		pI2CHandle->pI2Cx->I2C_CR2 |= (1 << I2C_CR2_ITERREN);

	}

	return busystate;
}




/*********************************************************************
 * @fn      		  - I2C_MasterHandleTXEInterrupt
 *
 * @brief             - Handles the TXE (Transmit Data Register Empty)
 *                      interrupt event in I2C master mode.
 *
 *                      This function is responsible for loading the next
 *                      byte of data into the I2C data register (DR) whenever
 *                      the TXE flag is set, indicating that the transmit
 *                      buffer is empty and ready for new data.
 *
 * @param[in]         - pI2CHandle : Pointer to I2C handle structure which
 *                                  contains transmit buffer pointer,
 *                                  remaining data length, state information,
 *                                  and I2C peripheral base address
 *
 * @return            - None
 *
 * @Note              - This function is called from the I2C event ISR when
 *                      the TXE interrupt occurs.
 *
 *                      Operation details:
 *                      - Checks if transmission is ongoing (I2C_BUSY_IN_TX)
 *                      - If TxLen > 0:
 *                          → Loads next byte from transmit buffer into DR register
 *                          → Increments buffer pointer
 *                          → Decrements TxLen
 *
 *                      - If TxLen becomes 0:
 *                          → Wait for BTF (Byte Transfer Finished) interrupt
 *                          → Final transmission steps handled in BTF handler
 *
 *                      Important flags involved:
 *                      - TXE = 1 → Data register empty, ready to send next byte
 *                      - BTF = 1 → Previous byte transfer completed on bus
 *
 *                      Internal members updated:
 *                      - pTxBuffer → Moves to next data byte
 *                      - TxLen     → Decreases as bytes are transmitted
 *
 *                      This function does NOT:
 *                      - Generate START or STOP condition
 *                      - Close transmission
 *                      - Handle completion callback
 *
 *                      Those operations are handled in:
 *                      - Address phase handler
 *                      - BTF interrupt handler
 *
 *********************************************************************/


void I2C_MasterHandleTXEInterrupt(I2C_Handle_t *pI2CHandle) {

	if (pI2CHandle->TxLen > 0) {
		//1. load the data into the register
		pI2CHandle->pI2Cx->I2C_DR = *(pI2CHandle->pTxBuffer);

		//2. decrement the TxLen
		pI2CHandle->TxLen--;

		//3. increment the buffer address
		pI2CHandle->pTxBuffer++;
					}


}

/*********************************************************************
 * @fn      		  - I2C_MasterHandleRXNEInterrupt
 *
 * @brief             - Handles RXNE interrupt in master mode.
 *                      Reads received data from DR register and stores
 *                      it into the receive buffer.
 *
 * @param[in]         - pI2CHandle : Pointer to I2C handle structure
 *
 * @return            - None
 *
 * @Note              - Called from ISR when RXNE flag is set.
 *                      Decrements RxLen and updates buffer pointer.
 *
 *********************************************************************/

void I2C_MasterHandleRXNEInterrupt(I2C_Handle_t *pI2CHandle)
{
	//we have to do the data reception

	if (pI2CHandle->RxSize == 1) {
		*pI2CHandle->pRxBuffer = pI2CHandle->pI2Cx->I2C_DR;
		pI2CHandle->RxLen--;
	}
	if (pI2CHandle->RxSize > 1) {
		if (pI2CHandle->RxLen == 2) {
			//clear the ack bit
			I2C_ManageAcking(pI2CHandle->pI2Cx, DISABLE);
		}
		//read dr
		*pI2CHandle->pRxBuffer =(uint8_t)pI2CHandle->pI2Cx->I2C_DR;
		pI2CHandle->pRxBuffer++;
		pI2CHandle->RxLen--;

	}
	if (pI2CHandle->RxLen == 0) {
		//close the I2C data reception and notify the application

		//1.genrate the stop condition
		if (pI2CHandle->sr == I2C_DISABLE_SR)
			I2C_GenerateStartCondition(pI2CHandle->pI2Cx);

		//2. close the I2C rx
		I2C_CloseReceiveData(pI2CHandle);

		//3.notify the application
		I2C_ApplicationEventCallback(pI2CHandle, I2C_EV_RX_CMPLT);

	}


}



/*********************************************************************
 * @fn      		  - I2C_EV_IRQHandling
 *
 * @brief             - Handles all I2C event interrupts (EV interrupts).
 *                      This function checks different I2C status flags
 *                      and calls corresponding helper functions to
 *                      handle each event during communication.
 *
 * @param[in]         - pI2CHandle : Pointer to I2C handle structure
 *                                  containing state, buffers, and
 *                                  peripheral base address
 *
 * @return            - None
 *
 * @Note              - This function is called from the I2C event ISR.
 *
 *                      It handles the following events:
 *
 *                      - SB (Start Bit):
 *                        → Indicates START condition generated
 *                        → Used to send slave address
 *
 *                      - ADDR (Address Matched):
 *                        → Indicates address phase completed
 *                        → Must be cleared by reading SR1 and SR2
 *
 *                      - BTF (Byte Transfer Finished):
 *                        → Indicates data transfer completed
 *                        → Used to generate STOP or continue transfer
 *
 *                      - TXE (Transmit Buffer Empty):
 *                        → Calls transmit handler to send next byte
 *
 *                      - RXNE (Receive Buffer Not Empty):
 *                        → Calls receive handler to read incoming data
 *
 *                      - STOPF (Stop Detection - Slave mode):
 *                        → Indicates STOP condition detected
 *
 *                      Based on current state:
 *                      - I2C_BUSY_IN_TX → Handles transmission events
 *                      - I2C_BUSY_IN_RX → Handles reception events
 *
 *                      This function does not directly process data,
 *                      it delegates tasks to:
 *                      - I2C_MasterHandleTXEInterrupt()
 *                      - I2C_MasterHandleRXNEInterrupt()
 *                      - Other helper functions
 *
 *********************************************************************/



void I2C_EV_IRQHandling(I2C_Handle_t *pI2CHandle) {
	//. interrupt handling for both master and slave mode of a device
	uint32_t temp1, temp2, temp3;

	temp1 = pI2CHandle->pI2Cx->I2C_CR2 & (1 << I2C_CR2_ITEVTEN);
	temp2 = pI2CHandle->pI2Cx->I2C_CR2 & (1 << I2C_CR2_ITBUFEN);

	temp3 = pI2CHandle->pI2Cx->I2C_SR1 & (1 << I2C_SR1_SB);

	//1. Handle the interrupt genrated by SB event
	//note.SB flag is only applicable in master mode
	if (temp1 && temp3)	//execute only temp1 and temp3 are set because it is interrupt handling so ITEVTEN flag must be set
			{
		//the interrupt is genrated because of the SB event
		//this block will not be executed in slave mode beacuse for slave SB is always zero
		// in this block lets executed the address phase
		if (pI2CHandle->TxRRxState == I2C_BUSY_IN_TX) {
			I2C_ExecuteAddressPhaseWrite(pI2CHandle->pI2Cx,
					pI2CHandle->DevAddr);
		} else if (pI2CHandle->TxRRxState == I2C_BUSY_IN_RX) {
			I2C_ExecuteAddressPhaseRead(pI2CHandle->pI2Cx, pI2CHandle->DevAddr);

		}

	}

	temp3 = pI2CHandle->pI2Cx->I2C_SR1 & (1 << I2C_SR1_ADDR);
	//2. Handle for the interrupt genrated by ADDR event
	//NOTE:when master mode : address is sent
	//when slave mode: Address matched with own address
	if (temp1 && temp3) {
		//ADDR flag is SET
		I2C_ClearADDRFlag(pI2CHandle);
	}

	temp3 = pI2CHandle->pI2Cx->I2C_SR1 & (1 << I2C_SR1_BTF);
//3. handle interrupt genrated by BTF (byte transfer finished) event
	if (temp1 && temp3) {
		//BTF flag is SET
		if (pI2CHandle->TxLen == 0) {
			if (pI2CHandle->TxRRxState == I2C_BUSY_IN_TX) {
				// make sure that TXE is also set
				if (pI2CHandle->pI2Cx->I2C_SR1 & (1 << I2C_SR1_TxE)) {
					//BTF,TXE=1  means stop communication by doing following

					//1.genrate the stop condition
					if (pI2CHandle->sr == I2C_DISABLE_SR)
						I2C_GenerateStopCondition(pI2CHandle->pI2Cx);

					//2.RST all the member elements of the handle strcutute
					I2C_CloseSendData(pI2CHandle);

					//3.notify the application about transmission completed
					I2C_ApplicationEventCallback(pI2CHandle, I2C_EV_TX_CMPLT);
				}
			}
		}
	}

	temp3 = pI2CHandle->pI2Cx->I2C_SR1 & (1 << I2C_SR1_STOPF);
	//4.Handle for interrupt genarated by STOPF event
	//note:STOP detection flag is applicable only slave mode: for master this flag never be set
	// the below code block will not be executed by the master since STOPF WILL NOT SET in master mode

	if (temp1 && temp3) {
		//STOPF flag is SET
		//clear the stop flag(i,e)read SR1 )and write to cr1)
		pI2CHandle->pI2Cx->I2C_CR1 |= 0x0000;

		//notify the application that stop is detected
		I2C_ApplicationEventCallback(pI2CHandle, I2C_EV_STOP);

	}

	temp3 = pI2CHandle->pI2Cx->I2C_SR1 & (1 << I2C_SR1_TxE);//txe means request for the data
	//5.Handle for interrupt genarated bt TXE event
	//for this we have to cheak temp1 temp2 and temp3 because it set when both ITEVFEN and ITBUFEN are set

	if (temp1 && temp2 && temp3) {
		//cheak for device mode
		if (pI2CHandle->pI2Cx->I2C_SR2 & (1 << I2C_SR2_MSL)) {
			//TXE flag is SET
			//WE have to do the data transmission
			if (pI2CHandle->TxRRxState == I2C_BUSY_IN_TX) {

				I2C_MasterHandleTXEInterrupt(pI2CHandle);
			}
		}else
		{
			//slave
			//maka sure that the slave is really in transmitter mode
			if(pI2CHandle->pI2Cx->I2C_SR2 & ( 1 << I2C_SR2_TRA))
			{
			I2C_ApplicationEventCallback(pI2CHandle, I2C_EV_DATA_REQ);
		}
		}
	}

	temp3 = pI2CHandle->pI2Cx->I2C_SR1 & (1 << I2C_SR1_RxNE);
	//6.handle for interrupt genarated by RxNE event
	if (temp1 && temp2 && temp3) {
		//cheak for the device mode
		if (pI2CHandle->pI2Cx->I2C_SR2 & (1 << I2C_SR2_MSL)) {
			//device is master
			//RXNE flag is SET
			if (pI2CHandle->TxRRxState == I2C_BUSY_IN_RX) {

				I2C_MasterHandleRXNEInterrupt(pI2CHandle);

		}

	}else
	{
		//slave
		//maka sure that the slave is really in transmitter mode
		if(pI2CHandle->pI2Cx->I2C_SR2 & ( 1 << I2C_SR2_TRA))
		{
		I2C_ApplicationEventCallback(pI2CHandle, I2C_EV_DATA_RCV);
	}
	}
	}
}





void I2C_SlaveSendData(I2C_RegDef_t *pI2C,uint8_t data )
{
	pI2C->I2C_DR=data;
}



uint8_t I2C_SlaveReceiveData(I2C_RegDef_t *pI2C)
{
	return  (uint8_t)pI2C->I2C_DR;
}











/*********************************************************************
 * @fn      		  - I2C_ER_IRQHandling
 *
 * @brief             - Handles all I2C error interrupts (ER interrupts).
 *                      This function checks error flags in the I2C status
 *                      register and takes appropriate action for each error.
 *
 * @param[in]         - pI2CHandle : Pointer to I2C handle structure
 *                                  containing state, buffers, and
 *                                  peripheral base address
 *
 * @return            - None
 *
 * @Note              - This function is called from the I2C error ISR.
 *
 *                      It handles the following error conditions:
 *
 *                      - BERR (Bus Error):
 *                        → Occurs due to illegal START/STOP condition
 *
 *                      - ARLO (Arbitration Lost):
 *                        → Occurs in multi-master communication
 *
 *                      - AF (Acknowledge Failure):
 *                        → Occurs when slave does not acknowledge
 *
 *                      - OVR (Overrun/Underrun):
 *                        → Data lost due to improper read/write timing
 *
 *                      - TIMEOUT:
 *                        → Communication timeout detected
 *
 *                      For each error:
 *                      - Corresponding flag is cleared
 *                      - Application callback is triggered
 *
 *                      User must implement:
 *                      I2C_ApplicationEventCallback()
 *                      to handle error events properly.
 *
 *********************************************************************/

void I2C_ER_IRQHandling(I2C_Handle_t *pI2CHandle)
{

	uint32_t temp1,temp2;

    //Know the status of  ITERREN control bit in the CR2
	temp2 = (pI2CHandle->pI2Cx->I2C_CR2) & ( 1 << I2C_CR2_ITERREN);


/***********************Check for Bus error************************************/
	temp1 = (pI2CHandle->pI2Cx->I2C_SR1) & ( 1<< I2C_SR1_BERR);
	if(temp1  && temp2 )
	{
		//This is Bus error

		//Implement the code to clear the buss error flag
		pI2CHandle->pI2Cx->I2C_SR1 &= ~( 1 << I2C_SR1_BERR);

		//Implement the code to notify the application about the error
	   I2C_ApplicationEventCallback(pI2CHandle,I2C_ERROR_BERR);
	}

/***********************Check for arbitration lost error************************************/
	temp1 = (pI2CHandle->pI2Cx->I2C_SR1) & ( 1 << I2C_SR1_ARLO );
	if(temp1  && temp2)
	{
		//This is arbitration lost error


		//Implement the code to clear the arbitration lost error flag
		pI2CHandle->pI2Cx->I2C_SR1 &= ~( 1 << I2C_SR1_ARLO);

		//Implement the code to notify the application about the error
		   I2C_ApplicationEventCallback(pI2CHandle,I2C_ERROR_ARLO);

	}

/***********************Check for ACK failure  error************************************/

	temp1 = (pI2CHandle->pI2Cx->I2C_SR1) & ( 1 << I2C_SR1_AF);
	if(temp1  && temp2)
	{
		//This is ACK failure error

	    //Implement the code to clear the ACK failure error flag
		pI2CHandle->pI2Cx->I2C_SR1 &= ~( 1 << I2C_SR1_AF);

		//Implement the code to notify the application about the error
		   I2C_ApplicationEventCallback(pI2CHandle,I2C_ERROR_AF);

	}

/***********************Check for Overrun/underrun error************************************/
	temp1 = (pI2CHandle->pI2Cx->I2C_SR1) & ( 1 << I2C_SR1_OVR);
	if(temp1  && temp2)
	{
		//This is Overrun/underrun

	    //Implement the code to clear the Overrun/underrun error flag
		pI2CHandle->pI2Cx->I2C_SR1 &= ~( 1 << I2C_SR1_OVR);

		//Implement the code to notify the application about the error
		   I2C_ApplicationEventCallback(pI2CHandle,I2C_ERROR_OVR);

	}

/***********************Check for Time out error************************************/
	temp1 = (pI2CHandle->pI2Cx->I2C_SR1) & ( 1 << I2C_SR1_TIMEOUT);
	if(temp1  && temp2)
	{
		//This is Time out error

	    //Implement the code to clear the Time out error flag
		pI2CHandle->pI2Cx->I2C_SR1 &= ~( 1 << I2C_SR1_TIMEOUT);

		//Implement the code to notify the application about the error
		   I2C_ApplicationEventCallback(pI2CHandle,I2C_ERROR_TIMEOUT);

	}

}






/*********************************************************************
 * @fn      		  - I2C_CloseReceiveData
 *
 * @brief             - Closes I2C data reception in interrupt mode.
 *                      Disables reception-related interrupts and
 *                      resets the handle structure to ready state.
 *
 * @param[in]         - pI2CHandle : Pointer to I2C handle structure
 *
 * @return            - None
 *
 * @Note              - This function is called after reception is complete.
 *
 *                      It performs the following:
 *                      - Disables RXNE and related interrupts
 *                      - Clears receive buffer pointer
 *                      - Resets RxLen and RxSize
 *                      - Sets TxRxState to I2C_READY
 *                      - Re-enables ACK (if previously disabled)
 *
 *********************************************************************/


void I2C_CloseReceiveData(I2C_Handle_t *pI2CHandle)
{
	//implement the code to disable ITBUFEN control bit
	pI2CHandle->pI2Cx->I2C_CR2 &=~(1 << I2C_CR2_ITBUFEN);

	//implement the code to disable  ITEVFEN control bit
	pI2CHandle->pI2Cx->I2C_CR2 &=~( 1 << I2C_CR2_ITEVTEN);

	pI2CHandle->TxRRxState=I2C_READY;
	pI2CHandle->pRxBuffer=NULL;
	pI2CHandle->RxLen=0;
	pI2CHandle->RxSize=0;
	if(pI2CHandle->I2C_Config.I2C_AckControl == I2C_ACK_ENABLE)
	{
    I2C_ManageAcking(pI2CHandle->pI2Cx, ENABLE);
	}

}

/*********************************************************************
 * @fn      		  - I2C_CloseSendData
 *
 * @brief             - Closes I2C data transmission in interrupt mode.
 *                      Disables transmission-related interrupts and
 *                      resets the handle structure to ready state.
 *
 * @param[in]         - pI2CHandle : Pointer to I2C handle structure
 *
 * @return            - None
 *
 * @Note              - This function is called after transmission is complete.
 *
 *                      It performs the following:
 *                      - Disables TXE and related interrupts
 *                      - Clears transmit buffer pointer
 *                      - Resets TxLen
 *                      - Sets TxRxState to I2C_READY
 *
 *********************************************************************/

void I2C_CloseSendData(I2C_Handle_t *pI2CHandle)
{
	//implement the code to disable ITBUFEN control bit
	pI2CHandle->pI2Cx->I2C_CR2 &=~(1 << I2C_CR2_ITBUFEN);

	//implement the code to disable  ITEVFEN control bit
	pI2CHandle->pI2Cx->I2C_CR2 &=~( 1 << I2C_CR2_ITEVTEN);

	pI2CHandle->TxRRxState=I2C_READY;
	pI2CHandle->pTxBuffer=NULL;
	pI2CHandle->TxLen=0;

}

/*********************************************************************
 * @fn      		  - I2C_ApplicationEventCallback
 *
 * @brief             - Weak application callback function for I2C events.
 *                      This function is called by the driver to notify
 *                      the application about communication events.
 *
 * @param[in]         - pI2CHandle : Pointer to I2C handle structure
 * @param[in]         - AppEv      : Event type indicating the status
 *                                  of I2C communication
 *
 * @return            - None
 *
 * @Note              - This is a weak implementation. User can override
 *                      this function in application code to handle events.
 *
 *                      Possible events:
 *                      - I2C_EV_TX_CMPLT  : Transmission complete
 *                      - I2C_EV_RX_CMPLT  : Reception complete
 *                      - I2C_ERROR_BERR   : Bus error
 *                      - I2C_ERROR_ARLO   : Arbitration lost
 *                      - I2C_ERROR_AF     : Acknowledge failure
 *                      - I2C_ERROR_OVR    : Overrun/Underrun error
 *                      - I2C_ERROR_TIMEOUT: Timeout error
 *
 *********************************************************************/

weak void I2C_ApplicationEventCallback(I2C_Handle_t *pI2CHandle,uint8_t AppEv)
{
    // This is a weak implementation
}



void I2C_SlaveEnbleDisbleCallbackEvents(I2C_RegDef_t *pI2Cx,uint8_t EnorDi)
{
	if(EnorDi== ENABLE)
	{
		pI2Cx->I2C_CR2 |= ( 1 << I2C_CR2_ITBUFEN);
		pI2Cx->I2C_CR2 |= ( 1 << I2C_CR2_ITERREN);
		pI2Cx->I2C_CR2 |= ( 1 << I2C_CR2_ITEVTEN);
	}else
	{
		    pI2Cx->I2C_CR2 &= ~( 1 << I2C_CR2_ITBUFEN);
			pI2Cx->I2C_CR2 &= ~( 1 << I2C_CR2_ITERREN);
			pI2Cx->I2C_CR2 &= ~( 1 << I2C_CR2_ITEVTEN);
	}
}




